---
- name: Set path to .bashrc
  ansible.builtin.set_fact:
    pyenv_bashrc_path: "{{ pyenv_home }}/.bashrc"
  when: pyenv_bashrc_path is undefined

- name: Check whether .bashrc file exists
  ansible.builtin.stat:
    path: "{{ pyenv_bashrc_path }}"
  register: pyenv_bashrc_st

- name: Resolve .bashrc symlink
  ansible.builtin.set_fact:
    pyenv_bashrc_path: "{{ pyenv_bashrc_st.stat.lnk_source }}"
  when: pyenv_bashrc_st.stat.exists and pyenv_bashrc_st.stat.islnk

- name: Check whether .pyenvrc is loaded in .bashrc
  ansible.builtin.command: >-
    grep -EFq 'source $HOME/.pyenv/.pyenvrc' {{ pyenv_bashrc_path }}
  register: check_bashrc
  ignore_errors: true
  changed_when: false
  failed_when: false
  when: pyenv_bashrc_st.stat.exists

- name: Load pyenv in .bashrc
  ansible.builtin.blockinfile:
    dest: "{{ pyenv_bashrc_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: pyenv"
    block: |
      if [ -e "$HOME/.pyenv/.pyenvrc" ]; then
        source $HOME/.pyenv/.pyenvrc
        if [ -e "$HOME/.pyenv/completions/pyenv.bash" ]; then
          source $HOME/.pyenv/completions/pyenv.bash
        elif [ -e "/usr/local/opt/pyenv/completions/pyenv.bash" ]; then
          source /usr/local/opt/pyenv/completions/pyenv.bash
        fi
      fi
  when: pyenv_bashrc_st.stat.exists and check_bashrc.rc != 0
